- hosts:  all
  become: yes
  tasks:
    - name: all 'control' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'control ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the control'
      authorized_key: user=control key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub